administrations/urls.py
from django.urls import path

from . import views

app_name = 'administrations'
#
urlpatterns = [
    path('', views.MainAdminView.as_view(), name='admin-main'),
    path('products/', views.ProductListAdminView.as_view(), name='admin-products'),
    path('brands/', views.BrandsAdminView.as_view(), name='admin-brands'),
    path('carts/', views.CartsAdminView.as_view(), name='admin-carts'),
    path('<str:who>/', views.AccountsAdminView.as_view(), name='admin-accounts'),
    path('products/<str:born>/', views.ProductAddAdminView.as_view(), name='admin-add-product'),
    path('ajax/product/delete/', views.ProductDeleteAdminView.as_view(), name='admin-delete-product'),
    path('ajax/account/delete/', views.AccountDeleteAdminView.as_view(), name='admin-delete-account'),
    path('ajax/cart/delete/', views.CartDeleteAdminView.as_view(), name='admin-delete-cart'),
    path('ajax/brand/delete/', views.BrandDeleteAdminView.as_view(), name='admin-delete-brand'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='cart'),
    path('ajax/add-cart-item/', views.AddCartItemView.as_view(), name='add-cart-item'),
    path('ajax/delete-cart-item/', views.DeleteCartItemView.as_view(), name='delete-cart-item'),
    path('ajax/update-cart-item-quantity/', views.UpdateCartItemQuantityView.as_view(), name='update-cart-item-quantity'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('detail/<int:pk>/', views.ProductDetailView.as_view(), name='product-details'),
    path('phones/<str:brand>/<str:cond>/', views.PhonesListView.as_view(), name='phones-list'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.CustomUserRegisterView.as_view(), name='user-register'),
    path('login/', views.CustomUserLoginView.as_view(), name='user-login'),
    path('logout/', views.CustomUserLogoutView.as_view(), name='user-logout'),
]

zuhrshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('administration/', include('administrations.urls')),
    path('', include('pages.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('user/', include('users.urls')),
    prefix_default_language=False,
)


if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/include/_accessory_create.html
<div class="form-row">
  <div class="form-group col-sm-6">
    <label for="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
    {{ form.name }}
  </div>
  <div class="form-group col-sm-3">
    <label for="{{ form.price.id_for_label }}">{{ form.price.label }}:</label>
    {{ form.price }}
  </div>
  <div class="form-group col-sm-3">
    <div class="form-check mb-2">
      {{ form.is_on_sale }}
      <label for="{{ form.is_on_sale.id_for_label }}" class="form-check-label">{{ form.is_on_sale.label }}:</label>
    </div>
    {{ form.on_sale_price }}
  </div>
</div>

<div class="form-row">
  <div class="form-group col-sm-6">
    <label for="{{ form.phone.id_for_label }}">{{ form.phone.label }}:</label>
    {{ form.phone }}
  </div>
  <div class="form-group col-sm-6">
    <label for="{{ form.material.id_for_label }}">{{ form.material.label }}:</label>
    {{ form.material }}
    <label for="{{ form.main_image.id_for_label }}">{{ form.main_image.label }}:</label>
    {{ form.main_image }}
  </div>
</div>

<div class="form-row">
  {{ formset.management_form }}
  {% for f in formset %}
    <div class="form-group col-sm-3">
      <label for="{{ f.image.id_for_label }}">{{ f.image.label }}:</label>
      {{ f.image }}
    </div>
  {% endfor %}
</div>

<div class="form-check mb-2">
  {{ form.is_available }}
  <label for="{{ form.is_available.id_for_label }}" class="form-check-label">{{ form.is_available.label }}:</label>
</div>

templates/include/_admin_footer.html
<footer class="tm-footer row tm-mt-small">
    <div class="col-12 font-weight-light">
        <p class="text-center text-white mb-0 px-4 small">
            Copyright &copy; <b>2018</b> All rights reserved.

            Design: <a rel="nofollow noopener" href="https://templatemo.com" class="tm-footer-link">Template Mo</a>
        </p>
    </div>
</footer>

templates/include/_admin_navbar.html
<nav id="sidebar">
  <div class="sidebar-header">
    <h3>ZuhrShop</h3>
    <strong>ZS</strong>
  </div>

  <ul class="list-unstyled components">
    <!-- <li class="active">
      <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
        <i class="fas fa-home"></i>
        Home
      </a>
      <ul class="collapse list-unstyled" id="homeSubmenu">
        <li><a href="#">Home 1</a></li>
        <li><a href="#">Home 2</a></li>
        <li><a href="#">Home 3</a></li>
        <li><a href="#">Home 4</a></li>
      </ul>
    </li> -->
    <li class="{% if url_name == 'dashboard' %}active{% endif %}">
      <a href="{% url 'administrations:admin-main' %}"><i class="fas fa-tachometer-alt"></i>
        Dashboard
      </a>
    </li>
    <li class="{% if url_name == 'products' %}active{% endif %}">
      <a href="{% url 'administrations:admin-products' %}">
        &nbsp;<i class="fas fa-mobile"></i>
        Products
      </a>
    </li>
    <li class="{% if url_name == 'carts' %}active{% endif %}">
      <a href="{% url 'administrations:admin-carts' %}"><i class="fas fa-shopping-cart"></i>
        Carts
      </a>
    </li>
    <li class="{% if url_name == 'clients' %}active{% endif %}">
      <a href="{% url 'administrations:admin-accounts' 'clients' %}"><i class="fas fa-users"></i>
        Clients
      </a>
    </li>
    <li class="{% if url_name == 'brands' %}active{% endif %}">
      <a href="{% url 'administrations:admin-brands' %}"><i class="far fa-copyright"></i>
        Brands
      </a>
    </li>
    <li class="{% if url_name == 'staff' %}active{% endif %}">
      <a href="{% url 'administrations:admin-accounts' 'staff' %}"><i class="fas fa-user-tie"></i>
        Staff
      </a>
    </li>
    <li>
      <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
        <i class="fas fa-copy"></i>
        Pages
      </a>
      <ul class="collapse list-unstyled" id="pageSubmenu">
        <li><a href="#">Page 1</a></li>
        <li><a href="#">Page 2</a></li>
        <li><a href="#">Page 3</a></li>
      </ul>
    </li>
  </ul>
</nav>

templates/include/_admin_top_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-lightm mb-4" id="forMessages" style="box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.1)">
    <div class="container-fluid">

        <button type="button" id="sidebarCollapse" class="navbar-btn">
            <span></span>
            <span></span>
            <span></span>
        </button>
        <ul class="nav navbar-nav ml-auto">
          <li class="nav-item">
            <a href="#" class="nav-link">Page</a>
          </li>
        </ul>
    </div>
</nav>

templates/include/_footer.html
{% load static %}
<footer class="bg-dark">
  <div class="container p-5">
    <div class="row">
      <div class="col-sm">
        <ul class="list-inline text-center text-light">
          <li class="list-inline-item"><a href="#" class="nav-link text-light"><i class="fa fa-facebook fa-2x"></i></a></li>
          <li class="list-inline-item"><a href="#" class="nav-link text-light"><i class="fa fa-instagram fa-2x"></i></a></li>
          <li class="list-inline-item"><a href="#" class="nav-link text-light"><i class="fa fa-google-plus fa-2x"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-sm">
        <ul class="list-inline text-center">
          <li class="list-inline-item"><a href="#" class="nav-link text-light">Service</a></li>
          <li class="list-inline-item"><a href="#" class="nav-link text-light">Contact</a></li>
          <li class="list-inline-item"><a href="#" class="nav-link text-light">About</a></li>
          <li class="list-inline-item"><a href="#" class="nav-link text-light">How to Use?</a></li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-sm">
        <p class="text-center text-light m-0">Languages</p>
        <ul class="list-inline text-center">
          <li class="list-inline-item"><a href="#" class="nav-link text-light"><img src="{% static 'images/en.png' %}" alt="en" width="25" height="25"></a></li>
          <li class="list-inline-item"><a href="#" class="nav-link text-light"><img src="{% static 'images/ru.png' %}" alt="ru" width="25" height="25"></a></li>
          <li class="list-inline-item"><a href="#" class="nav-link text-light"><img src="{% static 'images/uz.png' %}" alt="uz" width="25" height="25"></a></li>
        </ul>
      </div>
    </div>
    <p class="text-center m-0"><small class="text-muted">Copyright to SarCluMed - 2020</small></p>
  </div>
</footer>

templates/include/_message.html
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  {% endfor %}
{% endif %}

templates/include/_navbar.html
{% load static %}
{% load i18n %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-md mb-4">
  <a class="navbar-brand" href="/">Fleshka</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Phones
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <h6 class="dropdown-header">By brand</h6>
          {% for brand in brands %}
            <a class="dropdown-item text-capitalize" href="{% url 'product:phones-list' brand.name 'all' %}">{{ brand.name }}</a>
          {% endfor %}
          <div class="dropdown-divider"></div>
          <h6 class="dropdown-header">By condition</h6>
          <a class="dropdown-item" href="{% url 'product:phones-list' 'all' 'new' %}">New</a>
          <a class="dropdown-item" href="{% url 'product:phones-list' 'all' 'used' %}">Used</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'product:phones-list' 'all' 'all' %}">All</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Accessory
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <h6 class="dropdown-header">By category</h6>
          <a class="dropdown-item" href="#">Headphones</a>
          <a class="dropdown-item" href="#">Watches</a>
          <a class="dropdown-item" href="#">Cases</a>
          <a class="dropdown-item" href="#">Screen Protectors</a>
        </div>
      </li>
    </ul>

    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        {% if user.is_authenticated %}
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"">
            <i class="fa fa-user fa-2x align-middle">&nbsp;</i><span class="align-middle">{{ user.email }}</span>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a href="#" class="dropdown-item">
              <i class="fa fa-id-badge fa-2x align-middle">&nbsp;</i><span class="align-middle">History</span>
            </a>
            <a href="{% url 'users:user-logout' %}" class="dropdown-item">
              <i class="fa fa-sign-out fa-2x align-middle">&nbsp;</i><span class="align-middle">Logout</span>
            </a>
          </div>
        {% else %}
          <a href="{% url 'users:user-login' %}" class="nav-link">
            <i class="fa fa-user fa-2x align-middle">&nbsp;</i><span class="align-middle">LogIn</span>
          </a>
        {% endif %}
      </li>
      <li class="nav-item">
        <a href="{% url 'cart:cart' %}" class="nav-link">
          <i class="fa fa-shopping-cart fa-2x"></i><span class="badge badge-danger align-top" id="cart-badge-total">{{ cart.total_items_num }}</span>
        </a>
      </li>
    </ul>
  </div>
</nav>

templates/include/_phone_create.html
<div class="form-row">
  <div class="form-group col-sm-6">
    <label for="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
    {{ form.name }}
  </div>
  <div class="form-group col-sm-3">
    <label for="{{ form.price.id_for_label }}">{{ form.price.label }}:</label>
    {{ form.price }}
  </div>
  <div class="form-group col-sm-3">
    <div class="form-check mb-2">
      {{ form.is_on_sale }}
      <label for="{{ form.is_on_sale.id_for_label }}" class="form-check-label">{{ form.is_on_sale.label }}:</label>
    </div>
    {{ form.on_sale_price }}
  </div>
</div>

<div class="form-row">
  <div class="form-group col-sm-3">
    <label for="{{ form.ram.id_for_label }}">{{ form.ram.label }}:</label>
    {{ form.ram }}
  </div>
  <div class="form-group col-sm-3">
    <label for="{{ form.memory.id_for_label }}">{{ form.memory.label }}:</label>
    {{ form.memory }}
  </div>
  <div class="form-group col-sm-3">
    <label for="{{ form.camera.id_for_label }}">{{ form.camera.label }}:</label>
    {{ form.camera }}
  </div>
  <div class="form-group col-sm-3">
    <label for="{{ form.screen_dimension.id_for_label }}">{{ form.screen_dimension.label }}:</label>
    {{ form.screen_dimension }}
  </div>
</div>

<div class="form-row">
  <div class="form-group col-sm-3">
    <label for="{{ form.screen.id_for_label }}">{{ form.screen.label }}:</label>
    {{ form.screen }}
  </div>
  <div class="form-group col-sm-3">
    <label for="{{ form.brand.id_for_label }}">{{ form.brand.label }}:</label>
    {{ form.brand }}
  </div>
  <div class="form-group col-sm-3">
    <label for="{{ form.condition.id_for_label }}">{{ form.condition.label }}:</label>
    {{ form.condition }}
  </div>
  <div class="form-group col-sm-3">
    <label for="{{ form.main_image.id_for_label }}">{{ form.main_image.label }}:</label>
    {{ form.main_image }}
  </div>
</div>

<div class="form-row">
  {{ formset.management_form }}
  {% for f in formset %}
    <div class="form-group col-sm-3">
      <label for="{{ f.image.id_for_label }}">{{ f.image.label }}:</label>
      {{ f.image }}
    </div>
  {% endfor %}
</div>

<div class="form-check mb-2">
  {{ form.is_available }}
  <label for="{{ form.is_available.id_for_label }}" class="form-check-label">{{ form.is_available.label }}:</label>
</div>

templates/include/_product_card.html
<div class="card">
  <img src="{{ product.main_image.url }}" class="card-img-top" alt="">
  <div class="card-header">
    <h5 class="card-title" {% if product.is_on_sale %}style="text-decoration:line-through"{% endif %}>Price: {{ product.price }}</h5>
    {% if product.is_on_sale %}
      <h6 class="card-text">List: {{ product.on_sale_price }}</h6>
    {% endif %}
  </div>
  <div class="card-body">
    <p class="card-text text-capitalize">{{ product.name }} - {% if product.category == 'phone' %}{{ product.phone.memory }}GB{% endif %}</p>
    <a href="{% url 'product:phones-list' 'all' 'all' %}" class="card-link text-capitalize">{{ product.category }}</a>
  </div>
  <div class="card-footer">
    <a href="{% url 'product:product-details' product.id %}" class="btn btn-warning btn-block">See Details</a>
  </div>
</div>