administrations/urls.py
from django.urls import path

from . import views

app_name = 'administrations'
#
urlpatterns = [
    path('', views.MainAdminView.as_view(), name='admin-main'),
    path('products/', views.ProductListAdminView.as_view(), name='admin-products'),
    path('brands/', views.BrandsAdminView.as_view(), name='admin-brands'),
    path('carts/', views.CartsAdminView.as_view(), name='admin-carts'),
    path('<str:who>/', views.AccountsAdminView.as_view(), name='admin-accounts'),
    path('products/<str:born>/', views.ProductAddAdminView.as_view(), name='admin-add-product'),
    path('ajax/product/delete/', views.ProductDeleteAdminView.as_view(), name='admin-delete-product'),
    path('ajax/account/delete/', views.AccountDeleteAdminView.as_view(), name='admin-delete-account'),
    path('ajax/cart/delete/', views.CartDeleteAdminView.as_view(), name='admin-delete-cart'),
    path('ajax/brand/delete/', views.BrandDeleteAdminView.as_view(), name='admin-delete-brand'),
]

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='cart'),
    path('ajax/add-cart-item/', views.AddCartItemView.as_view(), name='add-cart-item'),
    path('ajax/delete-cart-item/', views.DeleteCartItemView.as_view(), name='delete-cart-item'),
    path('ajax/update-cart-item-quantity/', views.UpdateCartItemQuantityView.as_view(), name='update-cart-item-quantity'),
]

zuhrshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('administration/', include('administrations.urls')),
    path('', include('pages.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('user/', include('users.urls')),
    prefix_default_language=False,
)


if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administrations/models.py
from django.db import models

# Create your models here.

administrations/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.backends import BaseBackend
from django.http import Http404, JsonResponse
from django.core.exceptions import PermissionDenied

from users.models import CustomUser
from product.models import Product, ProductImage
from cart.models import Cart
from brands.models import Brand

from product.forms import PhoneCreationForm, ProductImageFormset, AccessoryCreationForm
from brands.forms import BrandCreationForm


class UserCheckingView(LoginRequiredMixin, UserPassesTestMixin):

    def test_func(self):
        if self.request.user.is_staff:
            return True
        else:
            return False


class MainAdminView(UserCheckingView, View):

    def get(self, request):

        context = {
            'url_name': 'dashboard',
        }
        return render(request, 'administrations/admin-main.html', context)


class ProductListAdminView(UserCheckingView, View):

    def get(self, request):
        # print(request.path)
        # a = request.path.split('/')[2]
        # print(a)
        # print(request.user.is_active)
        products = Product.objects.all()
        context = {
            'products': products,
            'url_name': 'products',
        }
        return render(request, 'administrations/admin-product.html', context)


class ProductAddAdminView(UserCheckingView, View):
    def get(self, request, born):
        if born == "phone":
            form = PhoneCreationForm()
        elif born == "accessory":
            form = AccessoryCreationForm()
        else:
            raise Http404("No such element")
        formset = ProductImageFormset(queryset=ProductImage.objects.none())
        context = {
            'form': form,
            'formset': formset,
            'born': born,
            'url_name': 'products',
        }
        return render(request, 'administrations/admin-add-product.html', context)

    def post(self, request, born):
        if born == 'phone':
            form = PhoneCreationForm(request.POST or None, request.FILES or None)
        elif born == 'accessory':
            form = AccessoryCreationForm(request.POST or None, request.FILES or None)
        else:
            raise PermissionDenied()
        formset = ProductImageFormset(request.POST or None, request.FILES or None)
        if form.is_valid() and formset.is_valid():
            product = form.save(commit=False)
            product.main_image = request.FILES['main_image']
            product.category = born
            product.save()
            print(formset.total_form_count())
            print(formset.initial_form_count())
            for f in formset:
                try:
                    image = ProductImage(product=product, image=f.cleaned_data['image'])
                    image.save()
                except KeyError as e:
                    break
                except Exception as e:
                    raise e

        return redirect('administrations:admin-products')


class ProductDeleteAdminView(UserCheckingView, View):
    def get(self, request):
        product_id = request.GET.get('product_id', None)
        if product_id is not None:
            Product.objects.get(id=product_id).delete()
            data = {
                'is_deleted': True
            }
        else:
            data = {
                'is_deleted': False
            }
        return JsonResponse(data)


class AccountsAdminView(UserCheckingView, View):

    def get(self, request, who):
        if who == 'staff':
            accounts = CustomUser.objects.filter(is_staff=True)
        elif who == 'clients':
            accounts = CustomUser.objects.filter(is_staff=False)
        else:
            raise Http404("Page Does Not Exist.")
        context = {
            'url_name': who,
            'accounts': accounts
        }
        return render(request, 'administrations/admin-accounts.html', context)


class AccountDeleteAdminView(UserCheckingView, View):
    def get(self, request):
        account_id = request.GET.get('account_id', None)
        if account_id is not None:
            user = CustomUser.objects.get(id=account_id)
            if not user.is_active:
                user.is_active = True
            else:
                user.is_active = False
            user.save()
            data = {
                'is_changed': True,
                'is_active': user.is_active
            }
        else:
            data = {
                'is_changed': False
            }
        return JsonResponse(data)


class BrandsAdminView(UserCheckingView, View):
    def get(self,  request):
        form = BrandCreationForm()
        context = {
            'url_name': 'brands',
            'form': form
        }
        return render(request, 'administrations/admin-brands.html', context)

    def post(self, request):
        form = BrandCreationForm(request.POST or None)
        if form.is_valid():
            form.save()
            return redirect('administrations:admin-brands')
        else:
            raise Http404()


class  BrandDeleteAdminView(UserCheckingView, View):
    def get(self, request):
        brand_id = request.GET.get('brand_id', None)
        if brand_id is not None:
            brand_obj = Brand.objects.get(id=brand_id)
            if brand_obj.phone_set.all():
                data = {
                    'is_deleted': False,
                    'message': 'There are products of this brand. Delete them first!'
                }
            else:
                Brand.objects.get(id=brand_id).delete()
                data = {
                    'is_deleted': True
                }
        else:
            data = {
                'is_deleted': False
            }
        return JsonResponse(data)


class CartsAdminView(UserCheckingView, View):
    def get(self, request):
        carts = Cart.objects.all()
        context = {
            'url_name': 'carts',
            'carts': carts,
        }
        return render(request, 'administrations/admin-carts.html', context)


class CartDeleteAdminView(UserCheckingView, View):
    def get(self, request):
        cart_id = request.GET.get('cart_id', None)
        if cart_id is not None:
            Cart.objects.get(id=cart_id).delete()
            data = {
                'is_deleted': True
            }
        else:
            data = {
                'is_deleted': False
            }
        return JsonResponse(data)

templates/administrations/admin-accounts.html
{% extends 'administrations/admin-base.html' %}
{% load static %}

{% block content %}
<h2 class="tm-block-title text-capitalize">{{ url_name }} List</h2>
<div class="" style="height:400px;overflow:auto;">
  <table class="table">
      <thead>
          <tr>
              <th scope="col">#</th>
              <th scope="col">ID NO.</th>
              <th scope="col">NAME</th>
              <th scope="col">EMAIL</th>
              <th scope="col">PHONE NO.</th>
              <th scope="col">ACTIVE ST.</th>
              <th scope="col">ACTION</th>
          </tr>
      </thead>
      <tbody>
          {% for account in accounts %}
            <tr id="account-{{ account.id }}">
                <th scope="row"><b>{{ forloop.counter }}</b></th>
                <td><b>{{ account.id }}</b></td>
                <td>{{ account.name }}</td>
                <td>{{ account.email }}</td>
                <td><b>{{ account.num }}</b></td>
                <td>
                  {% if account.is_active %}
                    <span class="badge badge-pill badge-success" id="badgeColor-{{ account.id }}"><i id="activeStatus-{{ account.id }}" class="fas fa-check"></i></span>
                  {% else %}
                    <span class="badge badge-pill badge-danger" id="badgeColor-{{ account.id }}"><i id="activeStatus-{{ account.id }}" class="fas fa-times"></i></span>
                  {% endif %}
                </td>
                <td>
                  <input type="hidden" id="Url" data-url="{% url 'administrations:admin-delete-account' %}" />
                  <button type="button" class="btn btn-outline-danger" onclick="deleteAccount({{ account.id }})">
                    <i class="fas fa-user"></i>
                  </button>
                </td>
            </tr>
          {% endfor %}
      </tbody>
  </table>
</div>
{% endblock %}

templates/administrations/admin-add-product.html
{% extends 'administrations/admin-base.html' %}

{% block content %}
<p class="text-right">
  {% if born == 'phone' %}
    <a href="{% url 'administrations:admin-add-product' 'accessory' %}"><i class="fas fa-plus" style="color:green"></i>Add <span class="text-success">Accessory</span> Instead</a>
  {% else %}
    <a href="{% url 'administrations:admin-add-product' 'phone' %}"><i class="fas fa-plus" style="color:green"></i>Add <span class="text-success">Phone</span> Instead</a>
  {% endif %}
</p>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-10">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <legend class="text-capitalize">create {{ born }}</legend>
        {% if born == 'phone' %}
          {% include 'include/_phone_create.html' %}
        {% elif born == 'accessory' %}
          {% include 'include/_accessory_create.html' %}
        {% else %}
          <h3 class="display-3">Ooops! Something went wrong...</h3>
        {% endif %}
        <button type="submit" class="btn btn-success">Create</button>
        <a href="{% url 'administrations:admin-products' %}" class="btn btn-outline-danger">Cancel</a>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/administrations/admin-base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fa/css/fontawesome.min.css' %}">
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'custom/css/jquery.mCustomScrollbar.min.css' %}"> -->
    <link rel="stylesheet" type="text/css" href="{% static 'custom/css/admin.css' %}">
    {% block stylesheets %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>

    <div class="wrapper">
      {% include 'include/_admin_navbar.html' %}
      <div id="content">
        {% include 'include/_admin_top_navbar.html' %}
        {% block content %}{% endblock %}
      </div>
    </div>

    {% block footer %}
    {% endblock %}


    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
    <script src="{% static 'custom/js/moment.min.js' %}"></script>
    <script src="{% static 'custom/js/Chart.min.js' %}"></script>
    <!-- <script src="{% static 'custom/js/jquery.mCustomScrollbar.concat.min.js' %}"></script> -->
    <script src="{% static 'custom/js/admin.js' %}"></script>
    {% block scripts %}
    {% endblock %}
  </body>
</html>

templates/administrations/admin-brands.html
{% extends 'administrations/admin-base.html' %}
{% load static %}

{% block content %}
<h2 class="tm-block-title text-capitalize">Brands List</h2>
<form class="form-inline mb-3" method="post">
  {% csrf_token %}
  {{ form.name }}
  <button type="submit" id="createBrand" class="btn btn-success ml-2">Create</button>
</form>
<div class="" style="height:400px;overflow:auto;">
  <table class="table">
      <thead>
          <tr>
              <th scope="col">#</th>
              <th scope="col">ID NO.</th>
              <th scope="col">NAME</th>
              <th scope="col">ACTION</th>
          </tr>
      </thead>
      <tbody>
          {% for brand in brands %}
            <tr id="brand-{{ brand.id }}">
                <th scope="row"><b>{{ forloop.counter }}</b></th>
                <td><b>{{ brand.id }}</b></td>
                <td>{{ brand.name }}</td>
                <td>
                  <input type="hidden" id="Url" data-url="{% url 'administrations:admin-delete-brand' %}" />
                  <button type="button" class="btn btn-outline-danger" onclick="deleteBrand({{ brand.id }})">
                    <i class="fas fa-trash"></i>
                  </button>
                </td>
            </tr>
          {% endfor %}
      </tbody>
  </table>
</div>
{% endblock %}

templates/administrations/admin-carts.html
{% extends 'administrations/admin-base.html' %}
{% load static %}

{% block content %}
<h2 class="tm-block-title text-capitalize">{{ url_name }} List - <i class="fas fa-shopping-cart"></i></h2>
<div class="" style="height:400px;overflow:auto;">
  <table class="table">
      <thead>
          <tr>
              <th scope="col">#</th>
              <th scope="col">ID NO.</th>
              <th scope="col">USER</th>
              <th scope="col">ACTION</th>
          </tr>
      </thead>
      <tbody>
          {% for cart in carts %}
            <tr id="cart-{{ cart.id }}">
                <th scope="row"><b>{{ forloop.counter }}</b></th>
                <td><b>{{ cart.id }}</b></td>
                <td>{{ cart.user }}</td>
                <td>
                  <input type="hidden" id="Url" data-url="{% url 'administrations:admin-delete-cart' %}" />
                  <button type="button" class="btn btn-outline-danger" onclick="deleteCart({{ cart.id }})">
                    <i class="fas fa-trash"></i>
                  </button>
                </td>
            </tr>
          {% endfor %}
      </tbody>
  </table>
</div>
{% endblock %}

templates/administrations/admin-main.html
{% extends 'administrations/admin-base.html' %}
{% load static i18n %}
{% block head %}
<style>
.sss {
    margin-top: 30vh;

}
.counter {
    font-size: 100px;
}
</style>
{% endblock %}
{% block body %}
{% get_current_language as LANGUAGE_CODE %}
<div class="container text-center">
    <div class="row sss">
        <div class="col-md-3">
            <h1><span class="counter">{{ tours }}</span></h1>
            <a href="#">
                <h3>{% trans 'Tours' %}</h3>
            </a>
        </div>
        <div class="col-md-2">
            <h1><span class="counter">{{ villas }}</span></h1>
            <a href="#">
                <h3>{% trans 'Villas' %}</h3>
            </a>
        </div>
        <div class="col-md-2">
            <h1><span class="counter">{{ sights }}</span></h1>
            <a href="#">
                {% if LANGUAGE_CODE == 'ru' %}<h3>Достоприме-<br>чательности</h3>{% else %} <h3>Sights</h3>{% endif %}
            </a>
        </div>
        <div class="col-md-2">
            <h1><span class="counter">{{news}}</span></h1>
            <a href="#">
                <h3>{% trans 'News' %}</h3>
            </a>
        </div>
        <div class="col-md-3">
            <h1><span class="counter ">{{cars}}</span></h1>
            <a href="#">
                <h3>{% trans 'Cars' %}</h3>
            </a>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<script src="{% static 'adminka/js/jquery.waypoints.js' %}"></script>
<script src="{% static 'adminka/js/jquery.counterup.js' %}"></script>
<script>
jQuery(document).ready(function($) {
    $('.counter').counterUp({
        delay: 30,
        time: 800
    });
});
</script>
{% endblock %}

templates/administrations/admin-product.html
{% extends 'administrations/admin-base.html' %}
{% load static i18n %}

{% block content %}
<h2>Products</h2>
<p>Filter:
  <a href="#" class="btn btn-info" onclick="filterCat(1)">Phones</a>
  <a href="#" class="btn btn-info" onclick="filterCat(2)">Accessory</a>
  <a href="#" class="btn btn-info" onclick="filterCat(0)">All</a>
</p>

<p class="text-right">
  <a href="{% url 'administrations:admin-add-product' 'phone' %}"class="mr-2"><i class="fas fa-plus" style="color:green"></i>Phone</a>
  <a href="{% url 'administrations:admin-add-product' 'accessory' %}"><i class="fas fa-plus" style="color:green"></i>Accessory</a>
</p>
<!-- <input type="radio" name="" value="Phone">
<input type="radio" name="" value="Accessory"> -->
<div class="" style="height:400px;overflow:auto;">
  <table class="table" id="productTable">
    <thead class="thead-info">
      <tr>
        <th scope="col" class="th" onclick="sortTableInt(-1)">#</th>
        <th scope="col" class="th" onclick="sortTableStr(0)">Name</th>
        <th scope="col" class="th" onclick="sortTableInt(1)">Price</th>
        <th scope="col">On sale</th>
        <th scope="col" class="th" onclick="sortTableStr(3)">Category</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for product in products %}
        <tr id="product-{{ product.id }}">
          <th scope="row" class="numer">{{ forloop.counter }}</th>
          <td class="text-capitalize">
            {% if product.category == 'phone' %}
              {{ product.phone.brand }} - {{ product.name }}
            {% else %}
              {{ product.accessory.material }} - {{ product.name }}
            {% endif %}
          </td>
          <td>
            {% if is_on_sale %}
              {{ product.on_sale_price }}
            {% else %}
              {{ product.price }}
            {% endif %}
          </td>
          <td>
            {% if product.is_on_sale %}
              <span class="badge badge-pill badge-success"><i class="fas fa-check"></i></span>
            {% else %}
              <span class="badge badge-pill badge-danger"><i class="fas fa-times"></i></span>
            {% endif %}
          </td>
          <td class="text-capitalize">{{ product.category }}</td>
          <td>
            <input type="hidden" id="Url" data-url="{% url 'administrations:admin-delete-product' %}" />
            <button type="button" class="btn btn-outline-danger" onclick="deleteProduct({{ product.id }})">
              <i class="fas fa-trash"></i>
            </button>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>



{% endblock %}