cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.CartView.as_view(), name='cart'),
    path('ajax/add-cart-item/', views.AddCartItemView.as_view(), name='add-cart-item'),
    path('ajax/delete-cart-item/', views.DeleteCartItemView.as_view(), name='delete-cart-item'),
    path('ajax/update-cart-item-quantity/', views.UpdateCartItemQuantityView.as_view(), name='update-cart-item-quantity'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('detail/<int:pk>/', views.ProductDetailView.as_view(), name='product-details'),
    path('phones/<str:brand>/<str:cond>/', views.PhonesListView.as_view(), name='phones-list'),
]

zuhrshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('administration/', include('administrations.urls')),
    path('', include('pages.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('user/', include('users.urls')),
    prefix_default_language=False,
)


if settings.DEBUG:
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from brands.models import Brand
from brands.models import NameField as LoweredField


class Product(models.Model):
    name = LoweredField(max_length=200)
    price = models.DecimalField(max_digits=100, decimal_places=2)
    is_on_sale = models.BooleanField(default=False)
    on_sale_price = models.DecimalField(max_digits=100, decimal_places=2, null=True, blank=True)
    is_available = models.BooleanField(default=True)
    main_image = models.ImageField(upload_to="product-images", default='phone.jpg')

    class Category(models.TextChoices):
        PHONE = 'phone', 'Phone'
        ACCESSORY = 'accessory', 'Accessory'

    category = models.CharField(max_length=10, choices=Category.choices, default=Category.PHONE)

    def __str__(self):
        return self.name


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="product-images")


class Phone(Product):

    class Condition(models.TextChoices):
        NEW = 'new', 'NEW'
        USED = 'used', 'USED'

    condition = models.CharField(max_length=4, choices=Condition.choices, default=Condition.NEW)
    ram = models.IntegerField(default=1)
    memory = models.IntegerField(default=1)
    camera = models.IntegerField(default=1)
    screen_dimension = models.FloatField(default=1)
    screen = LoweredField(max_length=200)
    brand = models.ForeignKey(Brand, on_delete=models.PROTECT)

    def __str__(self):
        return self.condition + '-' + self.name


class Accessory(Product):
    phone = models.ManyToManyField(Phone)
    material = LoweredField(max_length=200)

    def __str__(self):
        return self.name

product/forms.py
from django import forms
from .models import Phone, Accessory, ProductImage, Product
from brands.models import Brand

class MyCustomModelMultipleChoiceField(forms.ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.name


class GeneralProductForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Galaxy S100',
        'type': 'text'
    }))
    price = forms.DecimalField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': '1234.32',
        'step': "0.01",
        'type': 'number'
    }))
    is_on_sale = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={
        'class': 'form-check-input',
        'type': 'checkbox',
    }))
    on_sale_price = forms.DecimalField(required=False, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'On Sale Price',
        'step': "0.01",
        'type': 'number',
        'disabled': 'disabled'
    }))
    is_available = forms.BooleanField(required=False, initial=True, widget=forms.CheckboxInput(attrs={
        'class': 'form-check-input',
        'type': 'checkbox',
    }))
    main_image = forms.ImageField(widget=forms.ClearableFileInput(attrs={
        'class': 'form-control-file',
        'type': 'file'
    }))

    class Meta:
        model = Product
        fields = [
            'name',
            'price',
            'is_on_sale',
            'on_sale_price',
            'is_available',
            'main_image'
        ]


class PhoneCreationForm(GeneralProductForm):
    condition = forms.ChoiceField(choices=Phone.Condition.choices ,widget=forms.Select(attrs={
        'class': 'form-control'
    }))
    ram = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'placeholder': '4',
        'type': 'number'
    }))
    memory = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'placeholder': '32',
        'step': "0.01",
        'type': 'number'
    }))
    camera = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'placeholder': '12',
        'type': 'number'
    }))
    screen_dimension = forms.FloatField(widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'placeholder': '4.12',
        'step': "0.01",
        'type': 'number'
    }))
    screen = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Gorilla',
        'type': 'text'
    }))
    brand = forms.ModelChoiceField(queryset=Brand.objects.all(),
                                   widget=forms.Select(attrs={
                                                    'class': 'form-control'
                                                    }))

    class Meta:
        model = Phone
        fields = [
            'name', 'price', 'is_on_sale', 'on_sale_price', 'is_available',
            'main_image', 'condition', 'ram', 'memory', 'camera',
            'screen_dimension', 'screen', 'brand']


class AccessoryCreationForm(GeneralProductForm):
    phone = MyCustomModelMultipleChoiceField(queryset=Phone.objects.all(),
                                           widget=forms.SelectMultiple(attrs={
                                                'class': 'form-control'
                                           }))
    material = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Leather',
        'type': 'text'
    }))

    class Meta:
        model = Accessory
        fields = [
            'name', 'price', 'is_on_sale', 'on_sale_price', 'is_available',
            'main_image', 'phone', 'material']


ProductImageFormset = forms.modelformset_factory(
            ProductImage,
            fields=('image',),
            extra=4,
            max_num=4,
            widgets={'image': forms.ClearableFileInput(attrs={'class': 'form-control-file'})}
            )

product/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View

from .models import Product, Phone


class ProductDetailView(View):
    def get(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        if product.is_on_sale:
            off_percent = 100 * (1 - product.on_sale_price / product.price)
            off_percent = round(off_percent, 1)
            saved_money = product.price - product.on_sale_price
            context = {
                'product': product,
                'off_percent': off_percent,
                'saved_money': saved_money
            }
        else:
            context = {
                'product': product
            }
        return render(request, 'product/product-detail.html', context)


class PhonesListView(View):
    def get(self, request, brand, cond):
        products = Phone.objects.all()
        context = {
            'products': products,
            'current_brand': brand,
            'cond': cond,
        }
        return render(request, 'product/phones-list.html', context)

templates/product/phones-list.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<div class="row mt-3">

  <div class="col-sm-2">
    <div class="btn-group-vertical btn-block">
      <a href="{% url 'product:phones-list' 'all' cond %}" class="btn btn-light btn-sm {% if current_brand == 'all' %}active{% endif %}">All</a>
      {% for brand in brands %}
        <a href="{% url 'product:phones-list' brand.name cond %}" class="btn btn-light btn-sm text-capitalize {% if current_brand == brand.name %}active{% endif %}">{{ brand.name }}</a>
      {% endfor %}
    </div>

    <div class="btn-group-vertical btn-block">
      <a href="{% url 'product:phones-list' current_brand 'all' %}" class="btn btn-light btn-sm {% if cond == 'all' %}active{% endif %}">All</a>
      <a href="{% url 'product:phones-list' current_brand 'new' %}" class="btn btn-light btn-sm {% if cond == 'new' %}active{% endif %}">New</a>
      <a href="{% url 'product:phones-list' current_brand 'used' %}" class="btn btn-light btn-sm {% if cond == 'used' %}active{% endif %}">Used</a>
    </div>
  </div>

  <div class="col-sm-8">

      {% if products %}
        {% for product in products %}
            {% if forloop.counter0|divisibleby:3 %}
              {% if forloop.first %}
                <div class="card-group">
              {% else %}
                </div><div class="card-group">
              {% endif %}
            {% endif %}
              {% if product.phone.brand.name == current_brand %}
                {% if product.phone.condition == cond %}
                  {% include 'include/_product_card.html' %}
                {% elif cond == 'all' %}
                  {% include 'include/_product_card.html' %}
                {% endif %}
              {% elif current_brand == 'all' %}
                {% if product.phone.condition == cond %}
                  {% include 'include/_product_card.html' %}
                {% elif cond == 'all' %}
                  {% include 'include/_product_card.html' %}
                {% endif %}
              {% endif %}
            {% if forloop.last %}
              </div>
            {% endif %}
        {% endfor %}
      {% else %}
        <h1 class="display-1">Coming soon...</h1>
      {% endif %}

  </div>

  <div class="col-sm-2">
    <div class="card position-fixed">
      <div class="card-header">
        Ads
      </div>
      <ul class="list-group list-group-flush" style="position:sticky">
        <li class="list-group-item">New Phone</li>
        <li class="list-group-item">Trending Accessory</li>
        <li class="list-group-item">Watch by Apple</li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

templates/product/product-detail.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block stylesheets %}<link rel="stylesheet" type="" href="{% static 'custom/css/jquery.exzoom.css' %}">{% endblock %}

{% block content %}
  <p class="text-muted mb-auto text-capitalize">{{ product.category }}</p>
  <div class="row">

    <div class="col-sm-5">

      <!-- <div class="img-zoom-container">
        <img id="myimage" src="{{ product.main_image.url }}" alt="Product Image" class="img-fluid">
        <div id="myresult" class="img-zoom-result"></div>
      </div> -->

      <div class="exzoom" id="exzoom">
        <!-- Images -->
        <div class="exzoom_img_box">
          <ul class='exzoom_img_ul'>
            <li><img src="{{ product.main_image.url }}" alt=""></li>
            {% for product_image in product.productimage_set.all %}
              <li><img src="{{ product_image.image.url }}" alt=""></li>
            {% endfor %}
          </ul>
        </div>
        <!-- <a href="https://www.jqueryscript.net/tags.php?/Thumbnail/">Thumbnail</a> Nav-->
        <div class="exzoom_nav"></div>
        <!-- Nav Buttons -->
        <!-- <p class="exzoom_btn">
            <a href="javascript:void(0);" class="exzoom_prev_btn"> < </a>
            <a href="javascript:void(0);" class="exzoom_next_btn"> > </a>
        </p> -->
      </div>


    </div>

    <div class="col-sm-5">

      <a href="#" class="text-decoration-none text-capitalize">{% if product.category == 'phone' %} {{ product.phone.brand }}{% endif %}</a>

      <h1 class="text-muted text-capitalize">{{ product.name }} {% if product.category == 'phone' %} {{ product.phone.memory }}GB {% endif %}</h1>

      <p>
        <i class="fa fa-star" style="color:orange"></i>
        <i class="fa fa-star" style="color:orange"></i>
        <i class="fa fa-star" style="color:orange"></i>
        <i class="fa fa-star" style="color:orange"></i>
        <i class="fa fa-star"></i>
        - 4.1 average
      </p>

        <ul>
          <li class="text-capitalize">Name: {{ product.name }}</li>
          {% if product.category == 'phone' %}
            <li class="text-capitalize">Brand: {{ product.phone.brand }}</li>
            <li>Memory: {{ product.phone.memory }} GB</li>
            <li>Camera: {{ product.phone.camera }} Mega-pixels</li>
            <li class="text-capitalize">Screen: {{ product.phone.screen }}</li>
            <li>Screen dimension: {{ product.phone.screen_dimension }}'</li>
            <li class="text-capitalize"><b>Condition: {{ product.phone.condition }}</b></li>
          {% elif product.category == 'accessory' %}
            <li>For:
              <ul>
                {% for phone in product.accessory.phone_set %}
                  <li>{{ phone.name }}</li>
                {% endfor %}
              </ul>
            </li>
            <li>Material: {{ product.accessory.material }}</li>
          {% endif %}
        </ul>
      {% if product.is_on_sale %}
        <h4 class="text-danger">{{ product.on_sale_price }}$</h4>
        <h6>List Price: <del>{{ product.price }}$</del></h6>
        <h6>Save: {{ saved_money }}$ ({{ off_percent }}%)</h6>
      {% else %}
        <h6>Price: {{ product.price }}$</h6>
      {% endif %}
      <hr>
      <h2 class="text-bold">Consider Buying</h2>

    </div>

    <div class="col-sm-2">

      <div class="card">
        <ul class="list-group list-group-flush text-center" id="" style="position:sticky">
          <small class="text-muted text-center">Buy</small>
          <li class="list-group-item p-2">
            <input type="hidden" id="Url" data-url="{% url 'cart:add-cart-item' %}" />
            <button type="button" class="btn btn-warning btn-block p-0" onclick="addToCart({{ product.id }})">
              <span class="fa fa-shopping-cart fa-2x mr-3 align-middle"></span><span class="align-middle">Add to cart</span>
            </button>
          </li>
            <a href="#" class="list-group-link">Add to List</a>
            <li class="list-group-item p-2">
          </li>
        </ul>
      </div>

    </div>

  </div>
{% endblock %}

{% block scripts %}
  <script type="text/javascript" src="{% static 'custom/js/jquery.exzoom.js' %}"></script>
  <script type="text/javascript" src="{% static 'custom/js/cart-ops.js' %}"></script>
  <script type="text/javascript">

    $(function(){

      $("#exzoom").exzoom({
        // options here
        // thumbnail nav options
        "navWidth": 60,
        "navHeight": 60,
        "navItemNum": 5,
        "navItemMargin": 7,
        "navBorder": 1,

        // autoplay
        "autoPlay": false,

        // autoplay interval in milliseconds
        "autoPlayTimeout": 2000
      });

    });
  </script>
{% endblock %}